### ISSUE TITLE
Templating doesn't work in production with apache

### ISSUE THREAD

**Issue by felixhaeberle** [mgfagency/kirby-twig#10]
Hi, thanks for your help in advance.
We have a problem with displaying the twig based templating on a production server that runs Apache with the following error:

<img width="1437" alt="Screenshot 2020-02-12 00 30 15" src="https://user-images.githubusercontent.com/34959078/74289359-205d2b80-4d2f-11ea-92d7-b2727ff76454.png">

On local the code works fine using Laravel Valet.

We think the problem is related with twig, because when we add a default.php page, the default.php gets rendered properly. It's also strange that this message appears only when we want to access the root / of our website although we specified a custom front page for that `'home' => 'start'` in the config file (and therefore kirby should render start.twig and not default.php?). 
On the other pages it returns 500 Internal server error.

Can you help us with this?

Our template folder:

<img width="255" alt="Screenshot 2020-02-12 00 38 41" src="https://user-images.githubusercontent.com/34959078/74289714-11c34400-4d30-11ea-93fb-8961d21db663.png">

**Comment by seehat** [comment]
Hi felixhaeberle,

whats the name of the contentfile in your start folder?

**Comment by felixhaeberle** [comment]
We fixed this in the meantime, our deployment in production hadn't have the rights to write in the plugin folder so the plugin doesn't get installed. With installing the plugin properly we fixed this! Thanks for your help 🙏

**Comment by seehat** [comment]
Ok, good to know that it works now. Sry, that I couldn't help you more.
