### ISSUE TITLE
Use own plugin function in twig

### ISSUE THREAD

**Issue by felipep** [mgfagency/kirby-twig#2]
Hey I coded one plugin but I cannot call it on a twig template

my code looks like: 
````
// index.php from my-plugin

function foo($some_string) {
    return 'hello ' . $some_string;
}
````

````
// config.php
// in the past it was something like c::set('twig.function.foo', 'foo');

return [
   ...
    'twig.function.foo' => 'foo',
````

and my template
````
//some_template.twig

{{ foo('world') }}

````

But I got an error as response `Unknown "foo" function.`

**Comment by seehat** [comment]
Hi felipep, this is because the namespace of the config options changed. I'm sorry, that this has not been documented yet. Now it is. 

Use: `mgfagency.twig.function.foo`
