### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required '[...]/vendor/autoload.php'

### ISSUE THREAD

**Issue by bdecarne** [mgfagency/kirby-twig#3]
Hi there !

I'm trying to use this plugin in a composer install of Kirby.

I ran ```composer require mgfagency/kirby-twig``` in the root folder of the project. Plugin has been installed into the site/plugins directory, and vendors in the global vendor directory.

Know I get this error : ```PHP Fatal error:  require_once(): Failed opening required '[...]/vendor/autoload.php'```

The require line in the index.php does not seem to be necessary

**Comment by seehat** [comment]
Hi bdecarne, I will have a look tomorrow and prepare the plugin for the different installation methods.

**Comment by seehat** [comment]
This should be fixed in 1.0.7
