### ISSUE TITLE
open_basedir error in LoaderFilesystem.php

### ISSUE THREAD

**Issue by MathiasGmeiner** [mgfagency/kirby-twig#4]
It get an `open_basedir` error if I'm using kirby-twig on an Plesk Onyx installation with activated `open_basedir` restrictions. I'm not able to change the default value of `{WEBSPACEROOT}{/}{:}{TMP}{/}` (role restrictions).

It works fine if I remove these lines in `site/plugins/kirby-twig/src/classes/LoaderFilesystem.php`:

Line 219:
`$templatevariants[] = $shortname . '/' . $templatename . '.twig';`

Line 229:
`if (is_file($path.'/'.$templatevariant)) {`

Line 335:
`}`

**Comment by felipep** [comment]
I had the same problem with uberspace

**Comment by seehat** [comment]
Should be fixed in 1.0.8
